<?php

/**
 * Created by PhpStorm.
 * User: haohao
 * Date: 2017/8/23
 * Time: 下午2:55
 */
require_once 'man.php';

class people extends man
{
    public function __construct($age, $name)
    {
        parent::__construct($age, $name, '男');
    }

    public function hi()
    {
        echo 'man'.$this->getName().'sayhi';
//        parent::hi(); // TODO: Change the autogenerated stub
    }
}